# Generated by Django 4.2.17 on 2024-12-22 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_responsable_cursus', models.BooleanField(default=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Apprenti'), (3, 'Tuteur pédagogique'), (4, 'Enseignant'), (5, 'Maitre d apprentissage'), (6, 'coordinatrice d apprentissage'), (7, 'Entreprise')], default=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('siret', models.IntegerField(null=True)),
                ('adresse_entreprise', models.CharField(max_length=255, null=True)),
                ('nom_responsable', models.CharField(max_length=255, null=True)),
                ('prenom_responsable', models.CharField(max_length=255, null=True)),
                ('mission_apprenti', models.CharField(max_length=500, null=True)),
                ('type_contrat', models.CharField(max_length=255, null=True)),
                ('nom_du_referent', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntretienSemestriel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('semestre', models.IntegerField()),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.apprenti')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField(blank=True, null=True)),
                ('idApprenti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.apprenti')),
                ('idEcheance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('intitule', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite', models.IntegerField()),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.formation')),
            ],
        ),
        migrations.CreateModel(
            name='JournalDeFormation',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('date_derniere_modification', models.DateField(auto_now=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='FicheSynthese',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.journaldeformation')),
                ('document', models.FileField(blank=True, null=True, upload_to='ficheSyn_doc/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.journaldeformation')),
                ('document', models.FileField(blank=True, null=True, upload_to='presentation_doc/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportFinal',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.journaldeformation')),
                ('document', models.FileField(blank=True, null=True, upload_to='rapportFinal_doc/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportPING',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateurs.journaldeformation')),
                ('document', models.FileField(blank=True, null=True, upload_to='ping_doc/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TuteurPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuteur_pedagogique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_semestre', models.CharField(default='current', max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='utilisateurs.jury')),
                ('membre1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre1', to='utilisateurs.jury')),
                ('membre2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre2', to='utilisateurs.jury')),
            ],
        ),
        migrations.CreateModel(
            name='MaitreApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_maitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maitre_apprentissage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journaldeformation',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.semestre'),
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.entretiensemestriel')),
            ],
        ),
        migrations.AddField(
            model_name='entretiensemestriel',
            name='maitre_apprentissage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.maitreapprentissage'),
        ),
        migrations.AddField(
            model_name='entretiensemestriel',
            name='tuteur_pedagogique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.tuteurpedagogique'),
        ),
        migrations.CreateModel(
            name='CoordinatriceApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinatrice_apprentissage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apprenti',
            name='coordinatrice_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.coordinatriceapprentissage'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='entreprise_apprenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.entreprise'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.groupe'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='maitre_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.maitreapprentissage'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='numero_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.journaldeformation'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='tuteur_pedagogique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.tuteurpedagogique'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenti_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
