# Generated by Django 4.2.17 on 2024-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_apprenti_numero_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
