# Generated by Django 4.2.17 on 2025-01-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
