# Generated by Django 4.2.17 on 2025-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
