# Generated by Django 4.2.17 on 2025-01-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_event_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminder',
        ),
    ]
