# Generated by Django 4.2.17 on 2025-01-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_remove_event_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenti',
            name='numero_journal',
        ),
        migrations.AddField(
            model_name='apprenti',
            name='numero_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.journaldeformation'),
        ),
    ]
